name: Build

env:
  BUILD_VERSION: "7.0.${{github.run_number}}${{startsWith(github.ref, 'refs/heads/main') && '' || '-beta'}}"
  BUILD_INFORMATION: "7.0.${{github.run_number}}${{startsWith(github.ref, 'refs/heads/main') && '' || '-beta'}}+Branch.${{github.ref_name}}.Sha.${{github.sha}}"

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002
        volumes:
          - azurite_data:/data mcr.microsoft.com/azure-storage/azurite

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: 'dotnet build --no-restore --configuration Release -p:Version="${{env.BUILD_VERSION}}" -p:InformationalVersion="${{env.BUILD_INFORMATION}}"'

      - name: Test Project
        run: 'dotnet test --no-build --no-restore --configuration Release'

      - name: Create Packages
        if: success() && github.event_name != 'pull_request'
        run: 'dotnet pack --configuration Release --include-symbols --include-source --no-build --no-restore --output "${{github.workspace}}/artifacts" -p:PackageVersion="${{env.BUILD_VERSION}}"'

      - name: Upload Artifacts
        if: success() && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: artifacts
          path: '${{github.workspace}}/artifacts'

      - name: Publish Release Packages
        if: success() && startsWith(github.ref, 'refs/heads/main')
        run: |
          for package in $(find -name "${{github.workspace}}/artifacts/*.nupkg"); do
            echo "${0##*/}": Pushing $package...
            dotnet nuget push $package --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
          done

